// <auto-generated />
namespace MyAcademy_MVC_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_initialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_initialize));
        
        string IMigrationMetadata.Id
        {
            get { return "202601061502430_mig_initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
